name: Docker Image CI

on:
  push:
    branches: [ master,develop ]
  pull_request:
    branches: [ master,develop ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        DATE=$(date +%s)
        docker build . --file Dockerfile --tag laravel-ci:"${DATE}"
